import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { command } from "./command.mjs";
import { releaseChannel } from "./release-policy.mjs";

export const packageRoot = path.resolve(import.meta.dirname, "..");
const readJson = async file => JSON.parse(await readFile(file, "utf8"));
const json = value => `${JSON.stringify(value, null, 2)}\n`;
const registry = "https://registry.npmjs.org/";

/** Change npm identity metadata together; existing native provenance stays factual. */
export async function prepareVersion(root, version) {
  const release = releaseChannel(version);
  const pkg = await readJson(path.join(root, "package.json"));
  const lock = await readJson(path.join(root, "package-lock.json"));
  const manifest = await readJson(path.join(root, "generated/wasm-manifest.json"));
  assert.equal(pkg.name, "@drawmotive/textgraph");
  pkg.version = version;
  delete pkg.private;
  pkg.publishConfig = { access: "public", registry, tag: release.tag };
  lock.version = version;
  lock.packages[""].version = version;
  manifest.packageVersion = version;
  await writeFile(path.join(root, "package.json"), json(pkg));
  await writeFile(path.join(root, "package-lock.json"), json(lock));
  await writeFile(path.join(root, "generated/wasm-manifest.json"), json(manifest));
  await writeFile(path.join(root, "generated/wasm-manifest.js"), `export default ${JSON.stringify(manifest, null, 2)};\n`);
  return release;
}

/** Verify every generated byte before allowing it into a release artifact. */
export async function verifyPackage(root = packageRoot, gitTag) {
  const pkg = await readJson(path.join(root, "package.json"));
  const release = releaseChannel(pkg.version);
  assert.equal(pkg.name, "@drawmotive/textgraph", "Unexpected npm package");
  assert.notEqual(pkg.private, true, "Package is private");
  assert.deepEqual(pkg.publishConfig, { access: "public", registry, tag: release.tag }, "Unsafe publish configuration");
  if (gitTag) assert.equal(gitTag, release.gitTag, "Git tag does not match package version");
  const lock = await readJson(path.join(root, "package-lock.json"));
  assert.equal(lock.version, pkg.version, "Lockfile version mismatch");
  assert.equal(lock.packages[""].version, pkg.version, "Lockfile root version mismatch");
  const manifest = await readJson(path.join(root, "generated/wasm-manifest.json"));
  assert.equal(manifest.packageVersion, pkg.version, "Manifest version mismatch");
  assert.equal(manifest.packageName, pkg.name, "Manifest package mismatch");
  const projection = await readFile(path.join(root, "generated/wasm-manifest.js"), "utf8");
  assert.equal(projection, `export default ${JSON.stringify(manifest, null, 2)};\n`, "Manifest projection mismatch");
  assert.match(manifest.privateSource.commit, /^[a-f0-9]{40}$/, "Native source provenance missing");
  const paths = new Set();
  for (const asset of manifest.assets) {
    assert.match(asset.path, /^wasm\/[A-Za-z0-9_.-]+$/, "Unsafe asset path");
    assert.ok(!paths.has(asset.path), "Duplicate manifest asset");
    paths.add(asset.path);
    const bytes = await readFile(path.join(root, "generated", asset.path));
    assert.equal(bytes.length, asset.bytes, `Asset size mismatch: ${asset.path}`);
    assert.equal(createHash("sha256").update(bytes).digest("hex"), asset.sha256, `Asset hash mismatch: ${asset.path}`);
  }
  const diskPaths = (await readdir(path.join(root, "generated/wasm"))).map(name => `wasm/${name}`).sort();
  assert.deepEqual(diskPaths, [...paths].sort(), "Unmanifested runtime assets");
  return { ...release, name: pkg.name };
}

/** Inspect npm pack output, excluding private inputs and validating artifact identity. */
export function verifyPackList(packed, release) {
  assert.equal(packed.name, release.name, "Tarball package mismatch");
  assert.equal(packed.version, release.version, "Tarball version mismatch");
  assert.equal(packed.filename, `drawmotive-textgraph-${release.version}.tgz`, "Unexpected tarball filename");
  const files = packed.files.map(file => file.path);
  for (const required of ["package.json", "LICENSE", "README.md", "generated/wasm-manifest.json", "generated/wasm-manifest.js", "generated/wasm/NotoSans-LICENSE.txt", "generated/wasm/FuzzyBubbles-LICENSE.txt"]) {
    assert.ok(files.includes(required), `Required packed file missing: ${required}`);
  }
  for (const file of files) {
    // The asset copier is the only consumer script shipped in the package.
    if (file === 'scripts/copy-assets.mjs') continue;
    assert.ok(!/(?:^|\/)(?:\.git|\.env|\.npmrc|node_modules|scripts|test|language-packs)(?:\/|$)|\.(?:cs|pdb|map|ps1)$/.test(file), `Unpublishable file: ${file}`);
    assert.ok(/^(?:package.json|LICENSE|README.md|CHANGELOG.md|NOTICE|(?:src|generated|schemas|docs|examples)\/)/.test(file), `Unexpected packed path: ${file}`);
  }
}

/** Pack once; the receipt binds the version/channel and SHA-512 to those exact bytes. */
export async function packRelease(root = packageRoot, destination = path.join(root, ".release"), gitTag) {
  const release = await verifyPackage(root, gitTag);
  await mkdir(destination, { recursive: true });
  const { stdout } = await command("npm", ["pack", "--ignore-scripts", "--json", "--workspaces=false", "--pack-destination", destination], root);
  const [packed] = JSON.parse(stdout);
  verifyPackList(packed, release);
  const receipt = { ...release, filename: packed.filename, integrity: packed.integrity };
  await writeFile(path.join(destination, "release.json"), json(receipt));
  await verifyArtifact(destination, release);
  return receipt;
}

/** Reject modified artifacts and receipts before contacting the publication endpoint. */
export async function verifyArtifact(directory, expected) {
  const receipt = await readJson(path.join(directory, "release.json"));
  const release = releaseChannel(receipt.version);
  assert.equal(receipt.name, "@drawmotive/textgraph");
  for (const key of ["version", "tag", "gitTag"]) assert.equal(receipt[key], release[key], `Artifact ${key} mismatch`);
  if (expected) for (const key of ["name", "version", "tag", "gitTag"]) assert.equal(receipt[key], expected[key], `Artifact ${key} mismatch`);
  assert.equal(receipt.filename, `drawmotive-textgraph-${receipt.version}.tgz`);
  const bytes = await readFile(path.join(directory, receipt.filename));
  assert.equal(`sha512-${createHash("sha512").update(bytes).digest("base64")}`, receipt.integrity, "Artifact integrity mismatch");
  return receipt;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const [action, value, ...extra] = process.argv.slice(2);
  if (extra.length) throw new Error("Unexpected release arguments");
  let result;
  if (action === "prepare" && value) result = await prepareVersion(packageRoot, value);
  else if (action === "verify") result = await verifyPackage(packageRoot, value);
  else if (action === "pack") result = await packRelease(packageRoot, path.join(packageRoot, ".release"), value);
  else throw new Error("Usage: node scripts/release.mjs <prepare VERSION|verify [GIT_TAG]|pack [GIT_TAG]>");
  console.log(JSON.stringify(result, null, 2));
}
